model:
    n_hidden : 4
    hidden_size : 128
    batch_norm : False # NOTE: Can't be True if batch_size==1.
    activation : 'ReLU'

data: # (does it need to be nested?)
    # sites : ["CH-Dav"]
    sites_path: "tandc/tandc-physics/site_tandc_fluxnet2015_ameriflux_final_v2_iterative_training_selection.csv"
    pred_base_path : "tandc/tandc-physics-output/tandc_outputs_for_python"
    obs_base_path: "tandc/tandc-forcing"
    nPoints : 100 # -> decide if we want to truncate, what to do in training?
    exclude_negative : True

pipeline:
    predict_rs: True # If false, we predict gsCO2 instead, and convert it to rs.

train:
    lr: 4e-4
    epochs: 200
    weight_decay: 1e-6
    batch_size: 10
    test_split: 0.2
    seed: 24 # Assuming the data loading doesn't change, this ensures the test_split will be the same.
    hp_tuning: False # If this is true, hyperparameters are expected to be arrays.

wandb:
  use_wandb: False
  project: "change-project"
  tags: ['iterative_training']

name: iterative_training